export const PILOTS = [
  { id: 'nuka-marc', name: 'Nuka Marc', asset: 'nuka-marc', group: 'crew' },

  {
    id: "painter",
    name: "The Painter",
    asset: "the-painter",
    group: "crew",
  },
  {
    id: "bigzx",
    name: "Big ZX",
    asset: "bigzx",
    group: "crew",
  },
  {
    id: "jag",
    name: "JAG",
    asset: "jag",
    group: "crew",
  },
  {
    id: "wyldwolf",
    name: "WyldWolf",
    asset: "wyldwolf",
    group: "crew",
  },
  {
    id: "ducky",
    name: "Ducky",
    asset: "ducky",
    group: "crew",
  },
  {
    id: "amy",
    name: "Amy the Nuka Nightmare",
    asset: "amy-nuka-nightmare",
    group: "crew",
  },
  {
    id: "mayra",
    name: "Mayra Del Yermo",
    asset: "mayra-del-yermo",
    group: "crew",
  },
  {
    id: "coffee",
    name: "Coffee",
    asset: "coffee",
    group: "crew",
  },
  {
    id: "mm777",
    name: "MM777",
    asset: "mm777",
    group: "crew",
  },
  {
    id: "pettywiselol",
    name: "PettyWiselol",
    asset: "pettywiselol",
    group: "crew",
  },
  {
    id: "youyosong",
    name: "YouYosong",
    asset: "youyosong",
    group: "crew",
  },
  {
    id: "coconut",
    name: "Coconut",
    asset: "coconut",
    group: "crew",
  },
  {
    id: "bigndn1988",
    name: "BIGndn1988",
    asset: "bigndn1988",
    group: "crew",
  },
  {
    id: "retrochick24",
    name: "RetroChick24",
    asset: "retrochick24",
    group: "crew",
  },
  {
    id: "sharkbite07",
    name: "Sharkbite 07",
    asset: "sharkbite-07",
    group: "squad",
  },
  {
    id: "dukequackem",
    name: "Duke Quackem",
    asset: "duke-quackem",
    group: "squad",
  },
  {
    id: "quackshot01",
    name: "Quackshot 01",
    asset: "quackshot-01",
    group: "squad",
  },
  {
    id: "thunderbill02",
    name: "Thunderbill 02",
    asset: "thunderbill-02",
    group: "squad",
  },
  {
    id: "dustdart03",
    name: "Dust Dart 03",
    asset: "dust-dart-03",
    group: "squad",
  },
  {
    id: "mallardstorm04",
    name: "Mallardstorm 04",
    asset: "mallardstorm-04",
    group: "squad",
  },
  {
    id: "eggburner05",
    name: "Eggburner 05",
    asset: "eggburner-05",
    group: "squad",
  },
  {
    id: "nightbeak06",
    name: "Nightbeak 06",
    asset: "nightbeak-06",
    group: "squad",
  },
  {
    id: "sunfin07",
    name: "Sunfin 07",
    asset: "sunfin-07",
    group: "squad",
  },
  {
    id: "buzzbill08",
    name: "Buzzbill 08",
    asset: "buzzbill-08",
    group: "squad",
  },
  {
    id: "warwaddler09",
    name: "War Waddler 09",
    asset: "war-waddler-09",
    group: "squad",
  },
  {
    id: "novaquack10",
    name: "Nova Quack 10",
    asset: "nova-quack-10",
    group: "squad",
  },
  {
    id: "ace01",
    name: "Ace 01",
    asset: "ace-01",
    group: "squad",
  },
  {
    id: "barkhawk02",
    name: "Barkhawk 02",
    asset: "barkhawk-02",
    group: "squad",
  },
  {
    id: "spark03",
    name: "Spark 03",
    asset: "spark-03",
    group: "squad",
  },
  {
    id: "copilot04",
    name: "Copilot 04",
    asset: "copilot-04",
    group: "squad",
  },
  {
    id: "howler05",
    name: "Howler 05",
    asset: "howler-05",
    group: "squad",
  },
  {
    id: "rocket06",
    name: "Rocket 06",
    asset: "rocket-06",
    group: "squad",
  },
  {
    id: "astro07",
    name: "Astro 07",
    asset: "astro-07",
    group: "squad",
  },
  {
    id: "scrappy08",
    name: "Scrappy 08",
    asset: "scrappy-08",
    group: "squad",
  },
  {
    id: "peanut09",
    name: "Peanut 09",
    asset: "peanut-09",
    group: "squad",
  },
  {
    id: "nitro10",
    name: "Nitro 10",
    asset: "nitro-10",
    group: "squad",
  },

  {"id": "quackzar", "name": "Captain Quackzar", "asset": "quackzar", "group": "alien"},
  {"id": "ziggy-zorb", "name": "Ziggy Zorb", "asset": "ziggy-zorb", "group": "alien"},
  {"id": "princess-nebula", "name": "Princess Nebula", "asset": "princess-nebula", "group": "alien"},
  {"id": "gloop", "name": "Gloop", "asset": "gloop", "group": "alien"},
  {"id": "granny-galaxy", "name": "Granny Galaxy", "asset": "granny-galaxy", "group": "alien"},
  {"id": "bork-9000", "name": "Bork-9000", "asset": "bork-9000", "group": "alien"},
  {"id": "dj-moonbeam", "name": "DJ Moonbeam", "asset": "dj-moonbeam", "group": "alien"},
  {"id": "nibbles-invader", "name": "Nibbles the Invader", "asset": "nibbles-invader", "group": "alien"},
  {"id": "sheriff-starbeak", "name": "Sheriff Starbeak", "asset": "sheriff-starbeak", "group": "alien"},
  {"id": "oopsy-orbit", "name": "Oopsy Orbit", "asset": "oopsy-orbit", "group": "alien"},

  {"id": "count-quackula", "name": "Count Quackula", "asset": "count-quackula", "group": "halloween"},
  {"id": "patchwick", "name": "Patchwick", "asset": "patchwick", "group": "halloween"},
  {"id": "hex-hazel", "name": "Hex Hazel", "asset": "hex-hazel", "group": "halloween"},
  {"id": "mothlight", "name": "Mothlight", "asset": "mothlight", "group": "halloween"},
  {"id": "grim-waddler", "name": "Grim Waddler", "asset": "grim-waddler", "group": "halloween"},

  {"id": "jingle-jet", "name": "Jingle Jet", "asset": "jingle-jet", "group": "holiday"},
  {"id": "cocoa-comet", "name": "Cocoa Comet", "asset": "cocoa-comet", "group": "holiday"},
  {"id": "holly-haunt", "name": "Holly Haunt", "asset": "holly-haunt", "group": "holiday"},
  {"id": "kringle-claw", "name": "Kringle Claw", "asset": "kringle-claw", "group": "holiday"},
  {"id": "gobble-glider", "name": "Gobble Glider", "asset": "gobble-glider", "group": "holiday"},
  {"id": "maple-maven", "name": "Maple Maven", "asset": "maple-maven", "group": "holiday"},
  {"id": "midnight-mallard", "name": "Midnight Mallard", "asset": "midnight-mallard", "group": "newyear"},
  {"id": "confetti-comet", "name": "Confetti Comet", "asset": "confetti-comet", "group": "newyear"},
  {"id": "disco-dipper", "name": "Disco Dipper", "asset": "disco-dipper", "group": "newyear"},
  {"id": "sparkler-skip", "name": "Sparkler Skip", "asset": "sparkler-skip", "group": "newyear"},
  {"id": "mallard", "name": "Mallard", "asset": "mallard", "group": "quack"},
  {"id": "wood-duck", "name": "Wood Duck", "asset": "wood-duck", "group": "quack"},
  {"id": "mandarin-duck", "name": "Mandarin Duck", "asset": "mandarin-duck", "group": "quack"},
  {"id": "harlequin-duck", "name": "Harlequin Duck", "asset": "harlequin-duck", "group": "quack"},
  {"id": "northern-pintail", "name": "Northern Pintail", "asset": "northern-pintail", "group": "quack"},
  {"id": "northern-shoveler", "name": "Northern Shoveler", "asset": "northern-shoveler", "group": "quack"},
  {"id": "hooded-merganser", "name": "Hooded Merganser", "asset": "hooded-merganser", "group": "quack"},
  {"id": "bufflehead", "name": "Bufflehead", "asset": "bufflehead", "group": "quack"},
  {"id": "ruddy-duck", "name": "Ruddy Duck", "asset": "ruddy-duck", "group": "quack"},
  {"id": "king-eider", "name": "King Eider", "asset": "king-eider", "group": "quack"},
  {"id": "cinnamon-teal", "name": "Cinnamon Teal", "asset": "cinnamon-teal", "group": "quack"},
  {"id": "blue-winged-teal", "name": "Blue-winged Teal", "asset": "blue-winged-teal", "group": "quack"},
  {"id": "redhead", "name": "Redhead", "asset": "redhead", "group": "quack"},
  {"id": "canvasback", "name": "Canvasback", "asset": "canvasback", "group": "quack"},
  {"id": "american-wigeon", "name": "American Wigeon", "asset": "american-wigeon", "group": "quack"},
  {"id": "black-bellied-whistling-duck", "name": "Black-bellied Whistling-Duck", "asset": "black-bellied-whistling-duck", "group": "quack"},
  {"id": "canada-goose", "name": "Canada Goose", "asset": "canada-goose", "group": "honk"},
  {"id": "snow-goose", "name": "Snow Goose", "asset": "snow-goose", "group": "honk"},
  {"id": "white-fronted-goose", "name": "Greater White-fronted Goose", "asset": "white-fronted-goose", "group": "honk"},
  {"id": "brant", "name": "Brant", "asset": "brant", "group": "honk"},
  {"id": "barnacle-goose", "name": "Barnacle Goose", "asset": "barnacle-goose", "group": "honk"},
  {"id": "greylag-goose", "name": "Greylag Goose", "asset": "greylag-goose", "group": "honk"},
  {"id": "bar-headed-goose", "name": "Bar-headed Goose", "asset": "bar-headed-goose", "group": "honk"},
  {"id": "emperor-goose", "name": "Emperor Goose", "asset": "emperor-goose", "group": "honk"},
  {"id":"jetpack-penguin","name":"Penguin","asset":"jetpack-penguin","group":"grounded"},
  {"id":"jetpack-kiwi","name":"Kiwi","asset":"jetpack-kiwi","group":"grounded"},
  {"id":"jetpack-ostrich","name":"Ostrich","asset":"jetpack-ostrich","group":"grounded"},
  {"id":"jetpack-emu","name":"Emu","asset":"jetpack-emu","group":"grounded"},
  {"id":"jetpack-cassowary","name":"Cassowary","asset":"jetpack-cassowary","group":"grounded"},
  {"id":"jetpack-kakapo","name":"Kākāpō","asset":"jetpack-kakapo","group":"grounded"},
  {"id":"falcon-f16","name":"F-16 Falcon","asset":"falcon-f16","group":"jets"},
  {"id":"hornet-fa18","name":"F/A-18 Hornet","asset":"hornet-fa18","group":"jets"},
  {"id":"raptor-f22","name":"F-22 Raptor","asset":"raptor-f22","group":"jets"},
  {"id":"typhoon","name":"Eurofighter Typhoon","asset":"typhoon","group":"jets"},
  {"id":"rafale","name":"Dassault Rafale","asset":"rafale","group":"jets"},
  {"id":"gripen","name":"Saab Gripen","asset":"gripen","group":"jets"},
  {"id":"rivet-raccoon","name":"Rivet Raccoon","asset":"rivet-raccoon","group":"critters"},
  {"id":"captain-capy","name":"Captain Capy","asset":"captain-capy","group":"critters"},
  {"id":"foxtrot","name":"Foxtrot","asset":"foxtrot","group":"critters"},
  {"id":"otto-otter","name":"Otto Otter","asset":"otto-otter","group":"critters"},
  {"id":"poppy-panda","name":"Poppy Panda","asset":"poppy-panda","group":"critters"},
];
