export const PILOTS = [
  {
    id: "painter",
    name: "The Painter",
    asset: "the-painter",
    group: "crew",
  },
  {
    id: "bigzx",
    name: "Big ZX",
    asset: "bigzx",
    group: "crew",
  },
  {
    id: "wyldwolf",
    name: "WyldWolf",
    asset: "wyldwolf",
    group: "crew",
  },
  {
    id: "ducky",
    name: "Ducky",
    asset: "ducky",
    group: "crew",
  },
  {
    id: "amy",
    name: "Amy the Nuka Nightmare",
    asset: "amy-nuka-nightmare",
    group: "crew",
  },
  {
    id: "mayra",
    name: "Mayra Del Yermo",
    asset: "mayra-del-yermo",
    group: "crew",
  },
  {
    id: "coffee",
    name: "Coffee",
    asset: "coffee",
    group: "crew",
  },
  {
    id: "mm777",
    name: "MM777",
    asset: "mm777",
    group: "crew",
  },
  {
    id: "rocco",
    name: "Rocco",
    asset: "rocco",
    group: "crew",
  },
  {
    id: "pettywiselol",
    name: "PettyWiselol",
    asset: "pettywiselol",
    group: "crew",
  },
  {
    id: "youyosong",
    name: "YouYosong",
    asset: "youyosong",
    group: "crew",
  },
  {
    id: "coconut",
    name: "Coconut",
    asset: "coconut",
    group: "crew",
  },
  {
    id: "bigndn1988",
    name: "BIGndn1988",
    asset: "bigndn1988",
    group: "crew",
  },
  {
    id: "retrochick24",
    name: "RetroChick24",
    asset: "retrochick24",
    group: "crew",
  },
  {
    id: "docholiday",
    name: "Doc Holiday",
    asset: "doc-holiday",
    group: "crew",
  },
  {
    id: "sharkbite07",
    name: "Sharkbite 07",
    asset: "sharkbite-07",
    group: "squad",
  },
  {
    id: "dukequackem",
    name: "Duke Quackem",
    asset: "duke-quackem",
    group: "squad",
  },
  {
    id: "quackshot01",
    name: "Quackshot 01",
    asset: "quackshot-01",
    group: "squad",
  },
  {
    id: "thunderbill02",
    name: "Thunderbill 02",
    asset: "thunderbill-02",
    group: "squad",
  },
  {
    id: "dustdart03",
    name: "Dust Dart 03",
    asset: "dust-dart-03",
    group: "squad",
  },
  {
    id: "mallardstorm04",
    name: "Mallardstorm 04",
    asset: "mallardstorm-04",
    group: "squad",
  },
  {
    id: "eggburner05",
    name: "Eggburner 05",
    asset: "eggburner-05",
    group: "squad",
  },
  {
    id: "nightbeak06",
    name: "Nightbeak 06",
    asset: "nightbeak-06",
    group: "squad",
  },
  {
    id: "sunfin07",
    name: "Sunfin 07",
    asset: "sunfin-07",
    group: "squad",
  },
  {
    id: "buzzbill08",
    name: "Buzzbill 08",
    asset: "buzzbill-08",
    group: "squad",
  },
  {
    id: "warwaddler09",
    name: "War Waddler 09",
    asset: "war-waddler-09",
    group: "squad",
  },
  {
    id: "novaquack10",
    name: "Nova Quack 10",
    asset: "nova-quack-10",
    group: "squad",
  },
  {
    id: "ace01",
    name: "Ace 01",
    asset: "ace-01",
    group: "squad",
  },
  {
    id: "barkhawk02",
    name: "Barkhawk 02",
    asset: "barkhawk-02",
    group: "squad",
  },
  {
    id: "spark03",
    name: "Spark 03",
    asset: "spark-03",
    group: "squad",
  },
  {
    id: "copilot04",
    name: "Copilot 04",
    asset: "copilot-04",
    group: "squad",
  },
  {
    id: "howler05",
    name: "Howler 05",
    asset: "howler-05",
    group: "squad",
  },
  {
    id: "rocket06",
    name: "Rocket 06",
    asset: "rocket-06",
    group: "squad",
  },
  {
    id: "astro07",
    name: "Astro 07",
    asset: "astro-07",
    group: "squad",
  },
  {
    id: "scrappy08",
    name: "Scrappy 08",
    asset: "scrappy-08",
    group: "squad",
  },
  {
    id: "peanut09",
    name: "Peanut 09",
    asset: "peanut-09",
    group: "squad",
  },
  {
    id: "nitro10",
    name: "Nitro 10",
    asset: "nitro-10",
    group: "squad",
  },
];
