export const GATES_PER_WORLD = 8;
export const WORLDS = Object.freeze([
  { id: 'cinder-junction', name: 'Cinder Junction', subtitle: 'Where the last train never left.', terrain: 'THE ASHLINE', weather: 'dust', accent: '#ffba72', shadow: '#372b27', sky: '#6e9294', asset: 'worlds/cinder-junction.webp' },
  {"id": "area-quack-51", "name": "Area Quack-51", "subtitle": "Nothing to see. Especially overhead.", "terrain": "AREA QUACK-51", "weather": "stars", "accent": "#ffbd75", "shadow": "#172038", "sky": "#24304b", "asset": "worlds/area-quack-51.webp"},
  {"id": "pumpkin-hollow", "name": "Pumpkin Hollow", "subtitle": "The lanterns are watching.", "terrain": "PUMPKIN HOLLOW", "weather": "leaves", "accent": "#ffb45a", "shadow": "#352132", "sky": "#704a82", "asset": "worlds/pumpkin-hollow.webp"},
  {"id": "neon-spore-jungle", "name": "Neon Spore Jungle", "subtitle": "Please do not lick the mushrooms.", "terrain": "NEON SPORE JUNGLE", "weather": "stars", "accent": "#adffc8", "shadow": "#172038", "sky": "#24304b", "asset": "worlds/neon-spore-jungle.webp"},
  {"id": "amberleaf-crossing", "name": "Amberleaf Crossing", "subtitle": "Fall looks good on the wasteland.", "terrain": "AMBERLEAF CROSSING", "weather": "leaves", "accent": "#ffc875", "shadow": "#473326", "sky": "#86abc2", "asset": "worlds/amberleaf-crossing.webp"},
  {"id": "saturn-scrap-ring", "name": "Saturn’s Scrap Ring", "subtitle": "One planet’s trash. Your shortcut.", "terrain": "SATURN’S SCRAP RING", "weather": "stars", "accent": "#f6d493", "shadow": "#172038", "sky": "#24304b", "asset": "worlds/saturn-scrap-ring.webp"},
  { id: 'glowfen-marsh', name: 'Glowfen Marsh', subtitle: 'Follow the lights. Not the voices.', terrain: 'THE LOWLANDS', weather: 'fireflies', accent: '#a6f1af', shadow: '#112c2e', sky: '#376b76', asset: 'worlds/glowfen-marsh.webp' },
  {"id": "bubblegum-badlands", "name": "Bubblegum Badlands", "subtitle": "Sweet colors. Strange puddles.", "terrain": "BUBBLEGUM BADLANDS", "weather": "stars", "accent": "#ff9fdf", "shadow": "#172038", "sky": "#24304b", "asset": "worlds/bubblegum-badlands.webp"},
  {"id": "witchlight-woods", "name": "Witchlight Woods", "subtitle": "Take the path with fewer whispers.", "terrain": "WITCHLIGHT WOODS", "weather": "fireflies", "accent": "#a3f2a0", "shadow": "#182b30", "sky": "#336b7d", "asset": "worlds/witchlight-woods.webp"},
  {"id": "moon-cheese-outpost", "name": "Moon Cheese Outpost", "subtitle": "The moon has excellent snacks.", "terrain": "MOON CHEESE OUTPOST", "weather": "stars", "accent": "#ffe48c", "shadow": "#172038", "sky": "#24304b", "asset": "worlds/moon-cheese-outpost.webp"},
  {"id": "cider-mill-creek", "name": "Cider Mill Creek", "subtitle": "A little cider. A little chaos.", "terrain": "CIDER MILL CREEK", "weather": "leaves", "accent": "#edac60", "shadow": "#493a2b", "sky": "#b6b8a0", "asset": "worlds/cider-mill-creek.webp"},
  {"id": "jellyfish-nebula", "name": "Jellyfish Nebula", "subtitle": "Drift with the gentle giants.", "terrain": "JELLYFISH NEBULA", "weather": "stars", "accent": "#a9baff", "shadow": "#172038", "sky": "#24304b", "asset": "worlds/jellyfish-nebula.webp"},
  {"id": "ghostlight-midway", "name": "Ghostlight Midway", "subtitle": "All rides are a little haunted.", "terrain": "GHOSTLIGHT MIDWAY", "weather": "fireflies", "accent": "#e9afdf", "shadow": "#302438", "sky": "#785a9c", "asset": "worlds/ghostlight-midway.webp"},
  {"id": "martian-midnight-diner", "name": "Martian Midnight Diner", "subtitle": "Open all night. All three of them.", "terrain": "MARTIAN MIDNIGHT DINER", "weather": "stars", "accent": "#ff91b7", "shadow": "#172038", "sky": "#24304b", "asset": "worlds/martian-midnight-diner.webp"},
  { id: 'frostbite-relay', name: 'Frostbite Relay', subtitle: 'A lost signal at the edge of winter.', terrain: 'THE NORTH REACH', weather: 'snow', accent: '#a7def6', shadow: '#26304b', sky: '#1d2e58', asset: 'worlds/frostbite-relay.webp' },
  {"id": "upside-down-planet", "name": "The Upside-Down Planet", "subtitle": "Gravity took the day off.", "terrain": "THE UPSIDE-DOWN PLANET", "weather": "stars", "accent": "#b5f1df", "shadow": "#172038", "sky": "#24304b", "asset": "worlds/upside-down-planet.webp"},
  {"id": "crooked-snow-village", "name": "Crooked Snow Village", "subtitle": "Spooky meets snow day.", "terrain": "CROOKED SNOW VILLAGE", "weather": "snow", "accent": "#dbbafa", "shadow": "#242a49", "sky": "#283f71", "asset": "worlds/crooked-snow-village.webp"},
  {"id": "cosmic-pumpkin-colony", "name": "Cosmic Pumpkin Colony", "subtitle": "The harvest came from outer space.", "terrain": "COSMIC PUMPKIN COLONY", "weather": "stars", "accent": "#ffa965", "shadow": "#172038", "sky": "#24304b", "asset": "worlds/cosmic-pumpkin-colony.webp"},
  {"id": "moonbone-manor", "name": "Moonbone Manor", "subtitle": "The house has a few guests.", "terrain": "MOONBONE MANOR", "weather": "fireflies", "accent": "#a7dfff", "shadow": "#202c45", "sky": "#304977", "asset": "worlds/moonbone-manor.webp"},
  {"id": "mothership-disco", "name": "Mothership Disco", "subtitle": "Everybody aboard the groove.", "terrain": "MOTHERSHIP DISCO", "weather": "stars", "accent": "#ed9cff", "shadow": "#172038", "sky": "#24304b", "asset": "worlds/mothership-disco.webp"},
  {"id": "harvest-moon-fields", "name": "Harvest Moon Fields", "subtitle": "One more flight before supper.", "terrain": "HARVEST MOON FIELDS", "weather": "leaves", "accent": "#ffb774", "shadow": "#4f3040", "sky": "#ac6384", "asset": "worlds/harvest-moon-fields.webp"},
  { id: 'neon-spillway', name: 'Neon Spillway', subtitle: 'The power is out. The city isn’t.', terrain: 'THE AFTERLIGHT', weather: 'rain', accent: '#e9a1df', shadow: '#201d34', sky: '#25223c', asset: 'worlds/neon-spillway.webp' },
  {"id": "candy-corn-canyon", "name": "Candy Corn Canyon", "subtitle": "Sweet scenery. Questionable shortcuts.", "terrain": "CANDY CORN CANYON", "weather": "dust", "accent": "#ffc875", "shadow": "#5d342e", "sky": "#d38981", "asset": "worlds/candy-corn-canyon.webp"},
  {"id": "gobble-gulch", "name": "Gobble Gulch", "subtitle": "Please do not feed the mayor.", "terrain": "GOBBLE GULCH", "weather": "leaves", "accent": "#ffbf69", "shadow": "#553c28", "sky": "#e9ae64", "asset": "worlds/gobble-gulch.webp"},
]);
export function worldAt(gates = 0) {
  gates = Number.isFinite(gates) ? Math.max(0, gates) : 0;
  const stage = Math.floor(Math.max(0, Number.isFinite(gates) ? gates : 0) / GATES_PER_WORLD);
  return { ...WORLDS[stage % WORLDS.length], index: stage % WORLDS.length, stage, lap: Math.floor(stage / WORLDS.length) + 1, progress: Math.max(0, gates % GATES_PER_WORLD) / GATES_PER_WORLD };
}
export const assetUrl = path => new URL(`../assets/${path}`, import.meta.url).href;
